### PR TITLE
Inner pages responsive

### PR DESCRIPTION
**Pull request by BipinKalra**

### CODE REVIEW

**Comment by vdvibhu20** [comment]
Screenshot 2020-03-26 at 2 56 15 PM
margin bottom

**Comment by vdvibhu20** [comment]
Screenshot 2020-03-26 at 2 58 13 PM
margin in between

**Comment by vdvibhu20** [comment]
Screenshot 2020-03-26 at 3 03 51 PM
isko amoeba ki tarah hi handle karle

**Comment by vdvibhu20** [comment]
Screenshot 2020-04-03 at 12 27 24 PM
margin and job description issue still exists

**Comment by BipinKalra** [comment]
> Screenshot 2020-04-03 at 12 27 24 PM
> margin and job description issue still exists

margin vaala issue has been sorted in a-hire class of motley. theres a possibility ki voh missing ho is page pe.

**Comment by vdvibhu20** [comment]
> > Screenshot 2020-04-03 at 12 27 24 PM
> > margin and job description issue still exists
> 
> margin vaala issue has been sorted in a-hire class of motley. theres a possibility ki voh missing ho is page pe. and job description mein voh toggle hone vaala scene chahiye?

just put a-hire on a to level wrapper so that we don't have to specify it everywhere. 
yes job description toggle is also required.

**Pull request merged**
